### ISSUE TITLE
currently only working on a drag and drop?

### ISSUE THREAD

**Issue by nickfmc** [hitode909/vscode-zentabs#3]
this doesn't yet work on a doubleclick of a file in a file tree? or opening a file via ctrl+p  only works if you drag your file out?

**Comment by hitode909** [comment]
@nickfmc Thank you for reporting.
This is maybe because, files opened from a file tree is opened in preview mode.
- https://code.visualstudio.com/docs/getstarted/userinterface#_preview-mode
Previewing file will be closed immediately when you open next file.

I'm using VSCode with disabling the preview mode. Could you try these settings?

```
    "workbench.editor.enablePreviewFromQuickOpen": false,
    "workbench.editor.enablePreview": false
```

**Comment by nickfmc** [comment]
Awesome! That was it.  Works great now! thanks for the plugin.

**Comment by nickfmc** [comment]
One thing Also on this is that it does not remember the # of tabs when you re-open a project or open VSC .  if you have 6tabs open when you open VSC and your max is say 7 you will be able to open more than 1 tab probably 13 .  Not a big deal just need to remember to close all tabs when starting work

**Comment by hitode909** [comment]
@nickfmc Sorry for inconvenience. Currently, in VSCode, there is no way to collect all tabs from extension. This extension is recording tabs when it focused. So in your case, maximum size will be 7+6.

**Comment by dvdvdmt** [comment]
I think this information should be added in readme as important note.
I've made a pull request for that https://github.com/hitode909/vscode-zentabs/pull/7
